require('saif/themes/nightfox')
-- require('saif/themes/github-theme')
-- require('saif/themes/gruvbox-flat')
-- require('saif/themes/onedark')
-- require('saif/themes/material-nvim')
-- require('saif/themes/onenord')
-- require('saif/themes/gruvbox')
