require('saif/configs/telescope')
require('saif/configs/lualine')
require('saif/configs/treesitter')
require('saif/configs/auto-session')
require('saif/configs/nvim-autopairs')
require('saif/configs/nvim-ts-autotags')
require('saif/configs/spellsitter')
require('saif/configs/nvim-comment')
-- require('saif/configs/session-lens')
