require('saif/configs/telescope')
-- require('saif/configs/airline')
require('saif/configs/lualine')
require('saif/configs/treesitter')
require('saif/configs/auto-session')
require('saif/configs/nvim-autopairs')
require('saif/configs/nvim-ts-autotags')
-- require('saif/configs/pears')
require('saif/configs/spellsitter')
-- require('saif/configs/session-lens')
