require('saif/configs/telescope')
-- require('saif/configs/airline')
require('saif/configs/lualine')
require('saif/configs/treesitter')
require('saif/configs/auto-session')
require('saif/configs/pears')
-- require('saif/configs/session-lens')
